FROM node:18-alpine AS builder

ARG VITE_ZCRED_STORE_ORIGIN
ARG VITE_ZKAPP_HUB_ORIGIN

WORKDIR /app

COPY . .

RUN rm -r ./zcred-store
RUN rm -r ./zkapp-hub
RUN npm install -g pnpm
RUN pnpm run build
RUN rm -r ./zcred-store/src

FROM nginx:alpine-slim

COPY --from=builder /app/frontend/dist /usr/share/nginx/html
COPY /frontend/deployment/default.conf.template /etc/nginx/templates/default.conf.template