name: zcred-store-dev

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5445:5432"
    volumes:
      - ./db-dev-data:/var/lib/postgresql/data
