/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProveImport } from './routes/prove'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedCredentialsImport } from './routes/_authenticated/credentials'
import { Route as AuthenticatedCredentialIdImport } from './routes/_authenticated/credential.$id'

// Create/Update Routes

const ProveRoute = ProveImport.update({
  path: '/prove',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCredentialsRoute = AuthenticatedCredentialsImport.update({
  path: '/credentials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCredentialIdRoute = AuthenticatedCredentialIdImport.update({
  path: '/credential/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/prove': {
      preLoaderRoute: typeof ProveImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/credentials': {
      preLoaderRoute: typeof AuthenticatedCredentialsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/credential/$id': {
      preLoaderRoute: typeof AuthenticatedCredentialIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRouteRoute.addChildren([
    AuthenticatedCredentialsRoute,
    AuthenticatedCredentialIdRoute,
  ]),
  ProveRoute,
])

/* prettier-ignore-end */
